Theme.register('gruvbox', {
    mode: 'dark',
    backgrounds: [
        './src/themes/gruvbox/backgrounds/1-the-backwater.jpg',
        './src/themes/gruvbox/backgrounds/2-flower-basket.webp',
        './src/themes/gruvbox/backgrounds/3-village-square.jpg',
        './src/themes/gruvbox/backgrounds/4-idyllic-procession.jpg',
        './src/themes/gruvbox/backgrounds/5-leaves.jpg',
        './src/themes/gruvbox/backgrounds/omarchy.webp',
    ],
    colors: {
        accent: '#7daea3',
        selection: '#504945',
        muted: '#665c54',
        background: '#282828',
        dark_background: '#1e1e1e',
        darker_background: '#161616',
        lighter_background: '#3c3836',
        foreground: '#d4be98',
        dark_foreground: '#7c6f64',
        light_foreground: '#bdae93',
        bright_foreground: '#d4be98',
        red: '#ea6962',
        yellow: '#d8a657',
        orange: '#e1875c',
        green: '#a9b665',
        cyan: '#89b482',
        blue: '#7daea3',
        magenta: '#d3869b',
        brown: '#70432e',
        bright_red: '#ea6962',
        bright_yellow: '#d8a657',
        bright_green: '#a9b665',
        bright_cyan: '#89b482',
        bright_blue: '#7daea3',
        bright_magenta: '#d3869b',
    },
})
