Theme.register('tokyo-night', {
    mode: 'dark',
    backgrounds: [
        './src/themes/tokyo-night/backgrounds/0-winding-road.webp',
        './src/themes/tokyo-night/backgrounds/omarchy.webp',
        './src/themes/tokyo-night/backgrounds/1-quattro.webp',
        './src/themes/tokyo-night/backgrounds/2-swirl-buck.webp',
        './src/themes/tokyo-night/backgrounds/3-sunset-lake.webp',
        './src/themes/tokyo-night/backgrounds/4-omakub.webp',
        './src/themes/tokyo-night/backgrounds/5-oma-cityscape.jpg',
        './src/themes/tokyo-night/backgrounds/6-oma.webp',
    ],
    colors: {
        accent: '#7aa2f7',
        selection: '#292e42',
        muted: '#414868',
        background: '#1a1b26',
        dark_background: '#13141c',
        darker_background: '#0e0e14',
        lighter_background: '#24283b',
        foreground: '#a9b1d6',
        dark_foreground: '#565f89',
        light_foreground: '#b4bee6',
        bright_foreground: '#c0caf5',
        red: '#f7768e',
        yellow: '#e0af68',
        orange: '#eb927b',
        green: '#9ece6a',
        cyan: '#449dab',
        blue: '#7aa2f7',
        magenta: '#ad8ee6',
        brown: '#75493d',
        bright_red: '#ff7a93',
        bright_yellow: '#ff9e64',
        bright_green: '#b9f27c',
        bright_cyan: '#0db9d7',
        bright_blue: '#7da6ff',
        bright_magenta: '#bb9af7',
    },
})
