Theme.register('lupine', {
    mode: 'light',
    backgrounds: [
        './src/themes/lupine/backgrounds/01-cherry-blossom-bokeh.webp',
        './src/themes/lupine/backgrounds/02-cherry-blossom-white.webp',
        './src/themes/lupine/backgrounds/03-pastel-clouds.webp',
        './src/themes/lupine/backgrounds/04-elegant-blue-wave.webp',
        './src/themes/lupine/backgrounds/05-abstract-wave.webp',
        './src/themes/lupine/backgrounds/06-omarchy.webp',
    ],
    colors: {
        accent: '#3264eb',
        selection: '#d0d0d0',
        muted: '#9e9e9e',
        background: '#fafafa',
        dark_background: '#ececec',
        darker_background: '#dedede',
        lighter_background: '#f5f5f5',
        foreground: '#212121',
        dark_foreground: '#757575',
        light_foreground: '#424242',
        bright_foreground: '#000000',
        red: '#c900c4',
        yellow: '#026fde',
        orange: '#026fde',
        green: '#4a2fd0',
        cyan: '#0c67de',
        blue: '#3264eb',
        magenta: '#8a4ad7',
        brown: '#013a6f',
        bright_red: '#f930fb',
        bright_yellow: '#358fff',
        bright_green: '#9f85e0',
        bright_cyan: '#3986ff',
        bright_blue: '#5482ff',
        bright_magenta: '#b363ff',
    },
})
